stages:
  - bundle

.docker-build:
  dependencies: []
  variables:
    DOCKER_BUILDKIT: 1
    DOCKER_BUILDKIT_INLINE_CACHE: 1
    DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}
    DOCKER_IMAGE_TAG: latest
    DOCKER_IMAGE_PATH: .
  image: docker
  services:
    - docker:dind
  script:
    - echo -n ${CI_REGISTRY_PASSWORD} | docker login --username ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    - >
      docker build
      --build-arg BUILDKIT_INLINE_CACHE=${DOCKER_BUILDKIT_INLINE_CACHE}
      --cache-from ${DOCKER_IMAGE_NAME}:latest
      --pull
      --tag ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
      ${DOCKER_IMAGE_PATH}
    - docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

# bundle specific version (e.g. 1.0.0)
version:
  stage: bundle
  extends: .docker-build
  variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/

# bundle latest in default branch
latest:
  stage: bundle
  extends: .docker-build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
