name: Validate Dockerfile

on:
  push:
    branches:
      - *

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Lint dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
